### ISSUE TITLE
Couldn't process command: 'CraftingManager'

### ISSUE THREAD

**Issue by hektor157** [CreativeMD/CraftingManager#51]
I've tried command /CraftingManager on client and this is the error:
[Server thread/ERROR]: Couldn't process command: 'CraftingManager'
java.lang.NoClassDefFoundError: com/creativemd/craftingmanager/api/common/utils/entry/StateEntry
	at com.creativemd.craftingmanager.mod.core.CoreSystem.getEntries(CoreSystem.java:41) ~[CoreSystem.class:?]
	at com.creativemd.craftingmanager.mod.utils.server.ContainerConfig.<init>(ContainerConfig.java:67) ~[ContainerConfig.class:?]
	at com.creativemd.craftingmanager.mod.utils.GuiHandler.getServerGuiElement(GuiHandler.java:16) ~[GuiHandler.class:?]
	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) ~[NetworkRegistry.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209) ~[yz.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.showGui(CraftingManagerMod.java:151) ~[CraftingManagerMod.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.showGui(CraftingManagerMod.java:134) ~[CraftingManagerMod.class:?]
	at com.creativemd.craftingmanager.mod.utils.CommandGUI.func_71515_b(CommandGUI.java:56) ~[CommandGUI.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.ClassNotFoundException: com.creativemd.craftingmanager.api.common.utils.entry.StateEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 21 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/craftingmanager/api/common/utils/entry/TitleEntry
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 21 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.craftingmanager.api.common.utils.entry.TitleEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 21 more

and this error came up when i've tried same command on server

[Server thread/ERROR]: Caught exception from zcraftingmanager
java.lang.NoClassDefFoundError: com/creativemd/craftingmanager/api/core/ItemInfo
	at com.creativemd.craftingmanager.api.common.utils.string.ConvertInfo.getClassOfObject(ConvertInfo.java:15) ~[ConvertInfo.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringConverter.getConverter(StringConverter.java:42) ~[StringConverter.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringUtils.ObjectsToString(StringUtils.java:39) ~[StringUtils.class:?]
	at com.creativemd.craftingmanager.mod.furnace.FurnaceRecipe.RecipeToString(FurnaceRecipe.java:63) ~[FurnaceRecipe.class:?]
	at com.creativemd.craftingmanager.mod.furnace.disable.DisableFurnace.loadConfig(DisableFurnace.java:55) ~[DisableFurnace.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.serverStart(CraftingManagerMod.java:220) ~[CraftingManagerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:777) [Loader.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:287) [FMLCommonHandler.class:KCauldron-1.7.10-2.1403.1.54]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.creativemd.craftingmanager.api.core.ItemInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 35 more
Caused by: java.lang.SecurityException: class "com.creativemd.craftingmanager.api.core.ItemInfo"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.preDefineClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 35 more
[20:51:39] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/creativemd/craftingmanager/api/core/ItemInfo

	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:778) ~[Loader.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:287) ~[FMLCommonHandler.class:KCauldron-1.7.10-2.1403.1.54]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.NoClassDefFoundError: com/creativemd/craftingmanager/api/core/ItemInfo
	at com.creativemd.craftingmanager.api.common.utils.string.ConvertInfo.getClassOfObject(ConvertInfo.java:15) ~[ConvertInfo.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringConverter.getConverter(StringConverter.java:42) ~[StringConverter.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringUtils.ObjectsToString(StringUtils.java:39) ~[StringUtils.class:?]
	at com.creativemd.craftingmanager.mod.furnace.FurnaceRecipe.RecipeToString(FurnaceRecipe.java:63) ~[FurnaceRecipe.class:?]
	at com.creativemd.craftingmanager.mod.furnace.disable.DisableFurnace.loadConfig(DisableFurnace.java:55) ~[DisableFurnace.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.serverStart(CraftingManagerMod.java:220) ~[CraftingManagerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:777) ~[Loader.class:KCauldron-1.7.10-2.1403.1.54]
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.craftingmanager.api.core.ItemInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at com.creativemd.craftingmanager.api.common.utils.string.ConvertInfo.getClassOfObject(ConvertInfo.java:15) ~[ConvertInfo.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringConverter.getConverter(StringConverter.java:42) ~[StringConverter.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringUtils.ObjectsToString(StringUtils.java:39) ~[StringUtils.class:?]
	at com.creativemd.craftingmanager.mod.furnace.FurnaceRecipe.RecipeToString(FurnaceRecipe.java:63) ~[FurnaceRecipe.class:?]
	at com.creativemd.craftingmanager.mod.furnace.disable.DisableFurnace.loadConfig(DisableFurnace.java:55) ~[DisableFurnace.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.serverStart(CraftingManagerMod.java:220) ~[CraftingManagerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:777) ~[Loader.class:KCauldron-1.7.10-2.1403.1.54]
	... 3 more
Caused by: java.lang.SecurityException: class "com.creativemd.craftingmanager.api.core.ItemInfo"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.preDefineClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at com.creativemd.craftingmanager.api.common.utils.string.ConvertInfo.getClassOfObject(ConvertInfo.java:15) ~[ConvertInfo.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringConverter.getConverter(StringConverter.java:42) ~[StringConverter.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringUtils.ObjectsToString(StringUtils.java:39) ~[StringUtils.class:?]
	at com.creativemd.craftingmanager.mod.furnace.FurnaceRecipe.RecipeToString(FurnaceRecipe.java:63) ~[FurnaceRecipe.class:?]
	at com.creativemd.craftingmanager.mod.furnace.disable.DisableFurnace.loadConfig(DisableFurnace.java:55) ~[DisableFurnace.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.serverStart(CraftingManagerMod.java:220) ~[CraftingManagerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:777) ~[Loader.class:KCauldron-1.7.10-2.1403.1.54]
	... 3 more
[20:51:39] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoClassDefFoundError: com/creativemd/craftingmanager/api/core/ItemInfo
	at com.creativemd.craftingmanager.api.common.utils.string.ConvertInfo.getClassOfObject(ConvertInfo.java:15) ~[ConvertInfo.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringConverter.getConverter(StringConverter.java:42) ~[StringConverter.class:?]
	at com.creativemd.craftingmanager.api.common.utils.string.StringUtils.ObjectsToString(StringUtils.java:39) ~[StringUtils.class:?]
	at com.creativemd.craftingmanager.mod.furnace.FurnaceRecipe.RecipeToString(FurnaceRecipe.java:63) ~[FurnaceRecipe.class:?]
	at com.creativemd.craftingmanager.mod.furnace.disable.DisableFurnace.loadConfig(DisableFurnace.java:55) ~[DisableFurnace.class:?]
	at com.creativemd.craftingmanager.mod.CraftingManagerMod.serverStart(CraftingManagerMod.java:220) ~[CraftingManagerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:777) ~[Loader.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:287) ~[FMLCommonHandler.class:KCauldron-1.7.10-2.1403.1.54]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.creativemd.craftingmanager.api.core.ItemInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 35 more
Caused by: java.lang.SecurityException: class "com.creativemd.craftingmanager.api.core.ItemInfo"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.preDefineClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 35 more

I've tried both versions 0.7.5 and alpha but still there's the same error, what should i do?
Best Regards,
hektor157

**Comment by CreativeMD** [comment]
DragonAPI installed?

**Comment by hektor157** [comment]
Yes

**Comment by CreativeMD** [comment]
My mod has problems with DragonAPI. The author Reika is working on a fix, but it could take some more time. I will contact you as soon as it is out.

**Comment by hektor157** [comment]
Ah, Ok thanks for help, it's for to know that, I'll be waiting :)

**Comment by hektor157** [comment]
Hello,
any updates about compatibility with Reika's DragonAPI?
Because everytime when i try to use Crafting Mgr or anything on Core of yours it stops... so any updates or something?
I'd like to use "InGameConfigManager" and also "World Generation Manager"
Thanks.
Best Regards,
Hektor157 | HekTrack Consolidated Ltd.

**Comment by CreativeMD** [comment]
Nope no progress so far, i highly recommend to use InGameConfigManager, it doesn't have any issues with DragonAPI and it is a rewrite of CraftingManager.

**Comment by hektor157** [comment]
As i've told... i've tried InGameConfigManager but there's error on every start

**Comment by CreativeMD** [comment]
You can't use your old configs, if you are not using the old configs you could send me the crash-report.

**Comment by hektor157** [comment]
Ok, thanks for help, it works now i think

**Comment by CreativeMD** [comment]
ok :D
